# Google Cloud Build configuration for Cloud Run
steps:
  # Build the application
  - name: 'maven:3.8.6-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'backend'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/foodgo-backend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/foodgo-backend:latest', './backend']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/foodgo-backend:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/foodgo-backend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'foodgo-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/foodgo-backend:$SHORT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod'

images:
  - 'gcr.io/$PROJECT_ID/foodgo-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/foodgo-backend:latest'

